tsx_symbols = ['IFP.TO', 'CTC-A.TO', 'WFG.TO', 'ADW-B.TO', 'LAM.TO', 'AKT-B.TO', 'FVI.TO', 'ABX.TO', 'ACO-X.TO', 'AEM.TO', 'BBD-A.TO', 'BBD-B.TO', 'BMO.TO', 'BN.TO', 'BNS.TO', 'CAE.TO', 'CAS.TO', 'CCL-B.TO',
 'CCO.TO', 'CFP.TO', 'CGI.TO', 'CGO.TO', 'CM.TO', 'CNQ.TO', 'CSW-A.TO', 'DC-A.TO', 'DPM.TO', 'EMA.TO', 'EMP-A.TO', 'ENB.TO', 'FFH.TO', 'FTS.TO', 'FTT.TO', 'IGM.TO', 'IMO.TO', 'L.TO', 'LB.TO', 'LNR.TO', 'MATR.TO',
 'MRU.TO', 'MX.TO', 'NA.TO', 'ONEX.TO', 'POU.TO', 'POW.TO', 'QBR-A.TO', 'QBR-B.TO', 'RCI-A.TO', 'RCI-B.TO', 'RY.TO', 'SU.TO', 'T.TO', 'TA.TO', 'TCL-B.TO', 'TD.TO', 'TECK-B.TO', 'TPX-B.TO', 'UNC.TO', 'WCM-A.TO',
 'WN.TO', 'ALC.TO', 'CGY.TO', 'CWB.TO', 'MOGO.TO', 'SJ.TO', 'ACD.TO', 'SEA.TO', 'ADW-A.TO', 'ARE.TO', 'BOS.TO', 'DIAM.TO', 'ATS.TO', 'BLDP.TO', 'BTE.TO', 'BEI-UN.TO', 'BEK-B.TO', 'BHC.TO', 'CCM.TO', 'CIX.TO',
 'CTC.TO', 'ICE.TO', 'ASM.TO', 'ELD.TO', 'PAAS.TO', 'SSRM.TO', 'APS.TO', 'CCL-A.TO', 'CFW.TO', 'CIGI.TO', 'ESI.TO', 'GCG.TO', 'HRX.TO', 'LNF.TO', 'MPC.TO', 'MRD.TO', 'MTL.TO', 'OBE.TO', 'ORV.TO', 'PKI.TO', 'RCH.TO',
 'REI-UN.TO', 'VGZ.TO', 'XTC.TO', 'GBT.TO', 'BCE.TO', 'MAL.TO', 'AKT-A.TO', 'DII-A.TO', 'III.TO', 'LAS-A.TO', 'MFI.TO', 'TCL-A.TO', 'TKO.TO', 'AGF-B.TO', 'BRY.TO', 'EFR.TO', 'MXG.TO', 'NANO.TO', 'STC.TO', 'TAL.TO',
 'YGR.TO', 'ATD.TO', 'BLX.TO', 'GDL.TO', 'NPK.TO', 'TH.TO', 'AAB.TO', 'AOI.TO', 'AOT.TO', 'AVL.TO', 'BIR.TO', 'CNE.TO', 'CS.TO', 'CXB.TO', 'EDR.TO', 'EDV.TO', 'EXN.TO', 'FOM.TO', 'GEC.TO', 'GFP.TO', 'ITH.TO', 'KLS.TO',
 'LGO.TO', 'LUG.TO', 'LUN.TO', 'NDM.TO', 'NGD.TO', 'PRYM.TO', 'RUP.TO', 'SKE.TO', 'SVM.TO', 'TLG.TO', 'TSK.TO', 'AMM.TO', 'ARX.TO', 'BNE.TO', 'CCA.TO', 'CVG.TO', 'CWL.TO', 'DII-B.TO', 'EDT.TO', 'ELR.TO', 'EVT.TO',
 'FAP.TO', 'FTG.TO', 'GCG-A.TO', 'GIB-A.TO', 'GMX.TO', 'GSY.TO', 'HBP.TO', 'HLF.TO', 'HMM-A.TO', 'IMG.TO', 'MBX.TO', 'MDI.TO', 'MKP.TO', 'NG.TO', 'RUS.TO', 'S.TO', 'SEC.TO', 'SLR.TO', 'STN.TO', 'SXI.TO', 'TIH.TO', 'TVA-B.TO',
 'VET.TO', 'WDO.TO', 'WFC.TO', 'WJX.TO', 'WPK.TO', 'YRB.TO', 'CNR.TO', 'IMP.TO', 'WRG.TO', 'BR.TO', 'CMG.TO', 'TXP.TO', 'DML.TO', 'BDGI.TO', 'SAP.TO', 'HWX.TO', 'PEY.TO', 'BB.TO', 'PSI.TO', 'TWC.TO', 'ENGH.TO', 'FVL.TO',
 'ACO-Y.TO', 'BNG.TO', 'BUI.TO', 'CSW-B.TO', 'DIV.TO', 'DSG.TO', 'FT.TO', 'MCB.TO', 'MRE.TO', 'PIC-A.TO', 'SMT.TO', 'TCW.TO', 'TECK-A.TO', 'TGL.TO', 'VLN.TO', 'PTM.TO', 'GIL.TO', 'OTEX.TO', 'CLS.TO', 'TCS.TO', 'SGY.TO',
 'TOT.TO', 'MPVD.TO', 'BU.TO', 'SVA.TO', 'HR-UN.TO', 'CAR-UN.TO', 'CKI.TO', 'CJR-B.TO', 'PLZ-UN.TO', 'MFC.TO', 'WPRT.TO', 'QTRH.TO', 'BYD.TO', 'PNP.TO', 'USA.TO', 'SLF.TO', 'ATCU.TO', 'MEQ.TO', 'ONC.TO', 'MRT-UN.TO', 'FM.TO',
 'CU.TO', 'GVC.TO', 'DRX.TO', 'WM.TO', 'ELVA.TO', 'BEP-UN.TO', 'BDT.TO', 'KMP-UN.TO', 'DYA.TO', 'ETG.TO', 'SPB.TO', 'FRX.TO', 'CHE-UN.TO', 'CP.TO', 'OVV.TO', 'IIP-UN.TO', 'WCP.TO', 'JAG.TO', 'ARG.TO', 'WCN.TO', 'KEG-UN.TO',
 'ATRL.TO', 'ELF.TO', 'GWO.TO', 'K.TO', 'MRC.TO', 'NWC.TO', 'BPF-UN.TO', 'SWP.TO', 'FCR-UN.TO', 'PHX.TO', 'PMT.TO', 'ALS.TO', 'SIS.TO', 'FSY.TO', 'NVA.TO', 'GDC.TO', 'PSD.TO', 'SOY.TO', 'QEC.TO', 'X.TO', 'AGI.TO', 'AQN.TO',
 'CGG.TO', 'D-UN.TO', 'FC.TO', 'FRU.TO', 'KEY.TO', 'MAG.TO', 'NPI.TO', 'PPL.TO', 'RSI.TO', 'SRU-UN.TO', 'TFII.TO', 'TSL.TO', 'WTE.TO', 'CSH-UN.TO', 'FTN.TO', 'BSX.TO', 'RCG.TO', 'PRB.TO', 'SZLS.TO', 'DFN.TO', 'RPI-UN.TO',
 'CPH.TO', 'EQB.TO', 'ERD.TO', 'FSZ.TO', 'MGA.TO', 'RBA.TO', 'RVX.TO', 'SYZ.TO', 'EIF.TO', 'ALA.TO', 'AFN.TO', 'SAM.TO', 'CG.TO', 'MNO.TO', 'SOIL.TO', 'SRV-UN.TO', 'FFN.TO', 'GRT-UN.TO', 'HPS-A.TO', 'MG.TO', 'WPM.TO',
 'IFC.TO', 'AX-UN.TO', 'HBM.TO', 'PNE.TO', 'TLO.TO', 'LFE.TO', 'AIM.TO', 'BK.TO', 'FLNT.TO', 'TC.TO', 'E.TO', 'AEG.TO', 'PZA.TO', 'SBC.TO', 'MSV.TO', 'DCM.TO', 'UNI.TO', 'PD.TO', 'URE.TO', 'LUC.TO', 'CEU.TO', 'CF.TO',
 'CRR-UN.TO', 'SXP.TO', 'ENI-UN.TO', 'INC-UN.TO', 'MID-UN.TO', 'TBL.TO', 'U-UN.TO', 'CHW.TO', 'WRN.TO', 'ELEF.TO', 'SDE.TO', 'WILD.TO', 'MND.TO', 'MMP-UN.TO', 'ET.TO', 'DXT.TO', 'ORA.TO', 'MUX.TO', 'LBS.TO', 'DF.TO',
 'DR.TO', 'VCM.TO', 'URB.TO', 'PIF.TO', 'CFX.TO', 'CEE.TO', 'LCS.TO', 'PME.TO', 'TGO.TO', 'NCP.TO', 'HTL.TO', 'FAR.TO', 'XTD.TO', 'NCU.TO', 'CSU.TO', 'DNG.TO', 'ELO.TO', 'FTU.TO', 'GLO.TO', 'GRC.TO', 'HWO.TO', 'MARI.TO',
 'NOA.TO', 'OGC.TO', 'PDV.TO', 'PEA.TO', 'SGLD.TO', 'VLE.TO', 'VQS.TO', 'WEF.TO', 'XMF-A.TO', 'DGS.TO', 'FNV.TO', 'SFD.TO', 'SFI.TO', 'INE.TO', 'GLG.TO', 'SBR.TO', 'VNP.TO', 'BTO.TO', 'CRRX.TO', 'OLY.TO', 'TVE.TO', 'GTE.TO',
 'CRP.TO', 'TRI.TO', 'KEI.TO', 'LAAC.TO', 'SSL.TO', 'ADEN.TO', 'ADN.TO', 'AIF.TO', 'BDI.TO', 'BRE.TO', 'KBL.TO', 'PBH.TO', 'PBL.TO', 'ACQ.TO', 'AP-UN.TO', 'AYA.TO', 'DBM.TO', 'FN.TO', 'GH.TO', 'OGD.TO', 'SII.TO', 'SVI.TO',
 'WRX.TO', 'LIF.TO', 'CYB.TO', 'GAU.TO', 'TRZ.TO', 'CUP-U.TO', 'DBO.TO', 'BTB-UN.TO', 'MIN.TO', 'GCL.TO', 'OPT.TO', 'CPX.TO', 'BIP-UN.TO', 'DOL.TO', 'AAV.TO', 'AD-UN.TO', 'AUMN.TO', 'CVE.TO', 'PRU.TO', 'PHYS-U.TO', 'SCR.TO',
 'AC.TO', 'NWH-UN.TO', 'SES.TO', 'ATH.TO', 'SIA.TO', 'TXG.TO', 'GGD.TO', 'MTY.TO', 'CIQ-UN.TO', 'CFF.TO', 'NVO.TO', 'FDY.TO', 'AII.TO', 'ECOR.TO', 'MEG.TO', 'SAU.TO', 'WEED.TO', 'CGX.TO', 'PSLV-U.TO', 'SVB.TO', 'YCM.TO',
 'ARIS.TO', 'DS.TO', 'TOU.TO', 'XTG.TO', 'KRN.TO', 'GEO.TO', 'RTG.TO', 'KNT.TO', 'BKI.TO', 'SBI.TO', 'EFX.TO', 'PPTA.TO', 'ECO.TO', 'RBN-UN.TO', 'EFN.TO', 'BLN.TO', 'LN.TO', 'OGI.TO', 'CNT.TO', 'GEI.TO', 'MPC-C.TO', 'NEXT.TO',
 'NFI.TO', 'PNC-A.TO', 'PXT.TO', 'URB-A.TO', 'SGNL.TO', 'CDR.TO', 'CJT.TO', 'LGD.TO', 'CEF-U.TO', 'PNC-B.TO', 'ASND.TO', 'MRG-UN.TO', 'BLB-UN.TO', 'TMQ.TO', 'BABY.TO', 'BN-PF-A.TO', 'ENB-PF-U.TO', 'PYR.TO', 'QRC.TO', 'BCT.TO',
 'NCF.TO', 'IVQ-U.TO', 'AI.TO', 'BN-PF-B.TO', 'CXI.TO', 'FFH-U.TO', 'TPX-A.TO', 'WCM-B.TO', 'EXE.TO', 'DIR-UN.TO', 'IVN.TO', 'BN-PF-C.TO', 'KPT.TO', 'Y.TO', 'SPPP-U.TO', 'TNT-UN.TO', 'SOT-UN.TO', 'WELL.TO', 'OSK.TO', 'HOT-U.TO',
 'HOT-UN.TO', 'KEL.TO', 'FCD-UN.TO', 'HRR-UN.TO', 'INO-UN.TO', 'FCU.TO', 'MR-UN.TO', 'DOO.TO', 'DRM.TO', 'BN-PF-D.TO', 'CHP-UN.TO', 'ISV.TO', 'BGI-UN.TO', 'FSL-A.TO', 'VBNK.TO', 'ENB-PF-V.TO', 'CRT-UN.TO', 'GXE.TO', 'BYL.TO',
 'DRT.TO', 'CJ.TO', 'WSP.TO', 'MDP.TO', 'TVK.TO', 'GUD.TO', 'BN-PF-E.TO', 'ENB-PF-A.TO', 'PGI-UN.TO', 'SGR-UN.TO', 'ENB-PF-C.TO', 'PSK.TO', 'TD-PF-A.TO', 'BN-PF-F.TO', 'MKZ-UN.TO', 'KXS.TO', 'JOY.TO', 'VBG.TO', 'VBU.TO',
 'CIA.TO', 'EQX.TO', 'NXE.TO', 'MPCT-UN.TO', 'ENB-PF-E.TO', 'ILLM.TO', 'TD-PF-B.TO', 'SMC.TO', 'ENB-PF-G.TO', 'PRV-UN.TO', 'BN-PF-G.TO', 'DSV.TO', 'PUD-B.TO', 'PUD.TO', 'OR.TO', 'SCY.TO', 'QSR.TO', 'TD-PF-C.TO', 'CRON.TO',
 'FIH-U.TO', 'ESP.TO', 'TD-PF-D.TO', 'FF.TO', 'TTNM.TO', 'QSP-UN.TO', 'TD-PF-E.TO', 'XAU.TO', 'SHOP.TO', 'FSV.TO', 'RAY-A.TO', 'RAY-B.TO', 'TWM.TO', 'CRWN.TO', 'MDS-UN.TO', 'APR-UN.TO', 'TOY.TO', 'BN-PF-H.TO', 'H.TO',
 'PRQ.TO', 'DLCG.TO', 'CHR.TO', 'BBU-UN.TO', 'TF.TO', 'FIL.TO', 'ESM.TO', 'PPR.TO', 'ECN.TO', 'ATZ.TO', 'ACB.TO', 'FEC.TO', 'IPO.TO', 'BN-PF-I.TO', 'OLA.TO', 'AXIS.TO', 'KSI.TO', 'NUAG.TO', 'MDNA.TO', 'GOOS.TO', 'SHLE.TO',
 'IPCO.TO', 'TSND.TO', 'REAL.TO', 'FOOD.TO', 'JWEL.TO', 'TD-PF-I.TO', 'BN-PF-J.TO', 'TSU.TO', 'HFPC-U.TO', 'ERO.TO', 'TI.TO', 'ROOT.TO', 'STLC.TO', 'PRM.TO', 'PPL-PF-A.TO', 'NEO.TO', 'ENB-PF-K.TO', 'GRA.TO', 'NTR.TO',
 'CEF.TO', 'COG.TO', 'PHYS.TO', 'PSLV.TO', 'SPPP.TO', 'HUT.TO', 'HLS.TO', 'TD-PF-J.TO', 'AMC.TO', 'GENM.TO', 'HOM-U.TO', 'STGO.TO', 'XLY.TO', 'GDV.TO', 'AVNT.TO', 'ENS.TO', 'BRAG.TO', 'CTX.TO', 'FURY.TO', 'GDI.TO', 'GOLD.TO',
 'ORE.TO', 'PRN.TO', 'SIL.TO', 'STEP.TO', 'TNZ.TO', 'XTRA.TO', 'ERE-UN.TO', 'MI-UN.TO', 'CWEB.TO', 'AKU.TO', 'SOLG.TO', 'XAM.TO', 'ALYA.TO', 'CTS.TO', 'CRDL.TO', 'QIPT.TO', 'CNL.TO', 'LABS.TO', 'SFC.TO', 'LSPD.TO', 'NGT.TO',
 'ADCO.TO', 'TD-PF-M.TO', 'GRN.TO', 'HOM-UN.TO', 'APLI.TO', 'BITF.TO', 'AVCN.TO', 'EAGR.TO', 'IVQ.TO', 'DCBO.TO', 'AND.TO', 'URC.TO', 'PPL-PF-E.TO', 'EGLX.TO', 'GFL.TO', 'BIPC.TO', 'QBTC-U.TO', 'NUMI.TO', 'VOXR.TO', 'BNK.TO',
 'HBA.TO', 'SLS.TO', 'DND.TO', 'GLXY.TO', 'BEPC.TO', 'SIH-UN.TO', 'EXRO.TO', 'NVEI.TO', 'MHC-U.TO', 'PTI-UN.TO', 'TPZ.TO', 'QBTC.TO', 'GATO.TO', 'GURU.TO', 'NRR-UN.TO', 'RS.TO', 'QETH-U.TO', 'HAI.TO', 'AIDX.TO', 'QETH-UN.TO',
 'KITS.TO', 'TIXT.TO', 'NXR-UN.TO', 'GRID.TO', 'DHT-U.TO', 'DHT-UN.TO', 'WLLW.TO', 'ARR.TO', 'EPRX.TO', 'CLP-UN.TO', 'PAY.TO', 'BRMI.TO', 'NOVC.TO', 'G.TO', 'CURA.TO', 'MDA.TO', 'THNC.TO', 'TLRY.TO', 'LEV.TO', 'VRTS.TO',
 'TFPM.TO', 'PWI.TO', 'TFPM-U.TO', 'SFTC.TO', 'FORA.TO', 'STCK.TO', 'ANRG.TO', 'PTO-UN.TO', 'PET.TO', 'LSPK.TO', 'FLOW.TO', 'U-U.TO', 'BITC-U.TO', 'LCFS.TO', 'WNDR.TO', 'RBY.TO', 'VHI.TO', 'PWF-PF-A.TO', 'ASTL.TO', 'PRL.TO',
 'DTOL.TO', 'ASCU.TO', 'CVO.TO', 'DFY.TO', 'MSA.TO', 'GMTN.TO', 'TSAT.TO', 'GIVX.TO', 'ARA.TO', 'SGR-U.TO', 'PMZ-UN.TO', 'KEC.TO', 'BBUC.TO', 'PIX-UN.TO', 'MSRE-UN.TO', 'BLCO.TO', 'DRR-U.TO', 'MHC-UN.TO', 'IE.TO', 'AGRI-U.TO',
 'BAM.TO', 'BN-PF-K.TO', 'BN-PF-L.TO', 'PPL-PF-B.TO', 'LIRC.TO', 'AAUC.TO', 'DRR-UN.TO', 'LAC.TO', 'IGBT-UN.TO', 'PRMW.TO', 'RAV-UN.TO', 'CTF-UN.TO', 'EIT-UN.TO', 'JFS-UN.TO', 'PBY-UN.TO', 'SSF-UN.TO']

few_tsx = ['BAM.TO', 'BN-PF-K.TO', 'BN-PF-L.TO', 'PPL-PF-B.TO', 'LIRC.TO', 'AAUC.TO', 'DRR-UN.TO', 'LAC.TO', 'IGBT-UN.TO', 'PRMW.TO', 'RAV-UN.TO', 'CTF-UN.TO', 'EIT-UN.TO', 'JFS-UN.TO', 'PBY-UN.TO', 'SSF-UN.TO']

nasdaq1_symbols = ['AEP', 'LNT', 'ALCO', 'APOG', 'AVT', 'APA', 'AAME', 'ACNT', 'ADI', 'ADP', 'AGYS', 'AMAT', 'AMD', 'ARTW', 'ATRO', 'BRID', 'BSET',
       'CSWC', 'AROW', 'ABEO', 'ALNT', 'AAPL', 'ALOT', 'AMGN', 'ASYS', 'CAR', 'ANIX', 'CASY', 'BELFA', 'AIRT', 'BMRA', 'ASRV', 'ADSK',
       'ARKR', 'BCPC', 'ASTE', 'AMWD', 'ADBE', 'BKSC', 'AXGN', 'CRMT', 'BKR', 'AVNW', 'CDNS', 'CDZI', 'TECH', 'BLFS', 'BANF', 'ALKS',
       'BOKF', 'BIIB', 'ATNI', 'AMSC', 'APTO', 'ASUR', 'ARCB', 'AAON', 'AMRN', 'ANIK', 'AZN', 'BBSI', 'ARWR', 'ACHC', 'BCRX', 'ACNB',
       'CDMO', 'AXDX', 'ARTNA', 'ABCB', 'CCBG', 'ADTN', 'AMED', 'CARV', 'AZPN', 'AZTA', 'ACIW', 'ASML', 'AUBN', 'ACGL', 'ACHV', 'BANR',
       'BLDP', 'AEIS', 'ASTC', 'BYFC', 'ANDE', 'BOSC', 'AVDL', 'CASI', 'ANSS', 'CASS', 'AWRE', 'BJRI', 'BCDA', 'CALM', 'BKYI', 'AMZN',
       'OZK', 'AEHR', 'CAC', 'CWST', 'ASRT', 'BRKL', 'AMKR', 'CFFI', 'AXTI', 'DOX', 'BELFB', 'AEMD', 'BKNG', 'CFFN', 'ATLC', 'AUDC',
       'CTLP', 'BMRN', 'ARLP', 'AKAM', 'BGC', 'BMRC', 'AGEN', 'BBGI', 'ATLO', 'ANIP', 'ACLS', 'CAMT', 'BRKR', 'BOTJ', 'AWH', 'ALGN',
       'AXON', 'BGFV', 'CHI', 'CVGW', 'ACTG', 'ALRS', 'CHY', 'APDN', 'APWC', 'ATSG', 'ATHE', 'AYRO', 'BCLI', 'BHRB', 'BCBP', 'BFC',
       'ADEA', 'TBBK', 'BANFP', 'CSQ', 'ACAD', 'ALNY', 'ANGO', 'BIMI', 'BLKB', 'CRDF', 'GOOG', 'GOOGL', 'BECN', 'ARCC', 'ABVC', 'BVFL',
       'ALTO', 'BFIN', 'ATRC', 'BIDU', 'TCRT', 'AAL', 'CGO', 'BCML', 'BWEN', 'AMSF', 'CLMT', 'ATEC', 'AMTX', 'AVXL', 'BYRN', 'CSIQ',
       'ALLT', 'ALGT', 'RTC', 'AVAV', 'ARAY', 'PRTS', 'CAPR', 'CARE', 'FOLD', 'BLIN', 'ABUS', 'CHW', 'RILY', 'ACIC', 'ANTE', 'APEI',
       'AEHL', 'AACG', 'BPTH', 'AGNC', 'CPHC', 'AYTU', 'ASPS', 'AVGO', 'ADUS', 'BLNK', 'BWFG', 'AOSL', 'BEEM', 'BTCS', 'ASMB', 'ACST',
       'AMCX', 'BLRX', 'ANGI', 'BCOV', 'BCTX', 'CSTE', 'ASPU', 'TCPC', 'CG', 'BRFH', 'RCEL', 'BLMN', 'AMBA', 'ATOS', 'BRTX', 'AEYE',
       'ARCT', 'WTER', 'APCX', 'AGIO', 'DOOO', 'BYU', 'AAOI', 'ADMA', 'BANX', 'AKTX', 'CARA', 'CARM', 'AMRK', 'AKBA', 'BLBD', 'CGC',
       'ABTS', 'ALDX', 'AY', 'ARDX', 'BNTC', 'AMPH', 'ACB', 'CDNA', 'CCLD', 'ADVM', 'CYTO', 'AUPH', 'AFMD', 'CZR', 'CALA', 'ATRA',
       'BSGM', 'RENEW', 'ASND', 'AVGR', 'ATEX', 'BLPH', 'CCD', 'BPMC', 'ADAP', 'RKDA', 'BZUN', 'AKTS', 'ATXS', 'ALRM', 'APPF', 'AQMS',
       'ACRS', 'AVTX', 'CCLDP', 'CATC', 'AXSM', 'BDRX', 'TEAM', 'BGNE', 'BTCY', 'ABAT', 'AMLI', 'BATRA', 'BATRK', 'RNAC', 'APVO', 'BLBX',
       'ATOM', 'AIRG', 'ACIU', 'BL', 'AQB', 'ALPP', 'ANAB', 'POWW', 'BYSI', 'AFBI', 'APPN', 'ALT', 'CGBD', 'ATXI', 'ALRN', 'AREC',
       'BHF', 'AGNCN', 'ACGLO', 'FUV', 'CARG', 'AGAE', 'ALTR', 'ACMR', 'AHG', 'APLS', 'BAND', 'BOXL', 'ACET', 'CDLX', 'AADI', 'IONM',
       'ATXG', 'BTAI', 'BWB', 'BTBT', 'BIOX', 'BFI', 'ALBT', 'BRAG', 'BILI', 'AGMH', 'BFST', 'AHCO', 'XAIR', 'AUTL', 'BROG', 'BRY',
       'ALLK', 'AQST', 'JG', 'ADIL', 'AMAL', 'ARDS', 'ALAR', 'BNGO', 'BHFAL', 'BSVN', 'CBNK', 'ARVN', 'ALLO', 'BTCT', 'AMTB', 'AXNX',
       'APM', 'APYX', 'BWMX', 'CRDL', 'ADN', 'ALEC', 'ASLE', 'AGNCM', 'BPYPP', 'BHFAP', 'GOEV', 'BWAY', 'BYND', 'ATIF', 'APLT', 'BCYC',
       'ATER', 'AIRTP', 'AKRO', 'ARTL', 'CMBM', 'ADPT', 'BBIO', 'AFYA', 'ARKO', 'BHAT', 'BTOG', 'BITF', 'BPYPO', 'RILYN', 'AGNCO', 'APRE',
       'RILYP', 'BNTX', 'CABA', 'ASTS', 'AVPT', 'BLDE', 'CAN', 'CPZ', 'ADV', 'BSBK', 'ARQT', 'BDTX', 'AGNCP', 'BEAM', 'BPYPN', 'ADXN',
       'RILYM', 'BSFC', 'BHFAO', 'BNR', 'RNA', 'BIOR', 'API', 'ADTX', 'ACCD', 'ALXO', 'ANNX', 'ALVR', 'BIGC', 'AFIB', 'ANGH', 'AOUT',
       'RILYL', 'ABL', 'ATHA', 'BIVI', 'BSY', 'AMST', 'ASO', 'CCCC', 'ARRY', 'ALGS', 'BDSX', 'ALGM', 'ARBE', 'AVIR', 'BHFAN', 'SKIN',
       'AEI', 'SPRY', 'ABNB', 'ABCL', 'BCAB', 'AIMD', 'AMPG', 'AZ', 'BAFN', 'BGLC', 'LIDRW', 'LIDR', 'AFRM', 'RILYT', 'AGFY', 'BOLT',
       'BAOS', 'ADAG', 'BMBL', 'BVS', 'BNZI', 'AUUD', 'AMPGW', 'ASTL', 'BZFD', 'DRTS', 'ADSE', 'BAER', 'AFCG', 'DRUG', 'ACVA', 'AENT',
       'ALHC', 'ACHL', 'ARQQ', 'ALKT', 'APP', 'AKYA', 'BMEA', 'ALTI', 'AVAH', 'BTMD', 'BETR', 'BRNS', 'ANEB', 'BWMN', 'AISP', 'AUR',
       'ATCOL', 'CGABL', 'POWWP', 'ACGLN', 'CMAX', 'ATLCP', 'ALZN', 'ATAI', 'BON', 'ACXP', 'TKNO', 'AVTE', 'CDZIP', 'ABOS', 'AGRI',
       'BLFY', 'ABSI', 'CRBU', 'BPYPM', 'CADL', 'BTDR', 'RILYZ', 'BWBBP', 'ARBK', 'BRLT', 'CTCX', 'AMPL', 'AVDX', 'BBLG', 'BBLGW', 'AVHIU',
       'AIP', 'BNIX', 'AEAEU', 'AIRS', 'AURA', 'BFRI', 'BTTX', 'CCTSU', 'OZKAP', 'BIRD', 'ARHS', 'BCSAU', 'BJDX', 'BHFAM', 'BLZE', 'BTBD',
       'BRZE', 'ARBKL', 'AVHI', 'AHI', 'ATLCL', 'APLM', 'CNGLU', 'CMCAU', 'BENF', 'BOCNU', 'RILYG', 'APXIU', 'AEAE', 'ALSAU', 'BRKHU',
       'BNOX', 'AERT', 'ALLR', 'AOGOU', 'GMFIU', 'BCSA', 'CCTS', 'AMLX', 'CITEU', 'BRACU', 'ACABU', 'CDIO', 'AIBBU', 'ALSA', 'CNGL', 'CMCA',
       'APXI', 'BRKH', 'BWAQU', 'CCLDO', 'ACLX', 'AREB', 'AOGO', 'BOCN', 'AIB', 'BRAC', 'CITE', 'GMFI', 'ACAB', 'AKAN', 'ANTX', 'CAPT',
       'AFARU', 'APLD', 'BTM', 'ALCE', 'ACON', 'AIMAU', 'BLTE', 'ASCBU', 'RENEU', 'ASNS', 'BGXX', 'BNRG', 'ASCB', 'BCAN', 'AFAR', 'ALVO',
       'RENE', 'ARQQW', 'ASTI', 'AGNCL', 'AQUNU', 'AQU', 'ASPI', 'ATAT', 'ACRV', 'JEWL', 'ATMVU', 'ATLX', 'ATMCU', 'ATMC', 'CVKD', 'ATMV',
       'BREA', 'ASST', 'AWIN', 'BLACU', 'BFRG', 'BMR', 'BLAC', 'APLMW', 'ARBB', 'SLRN', 'ALCYU', 'CWD', 'CALC', 'CISS', 'CSWCZ', 'BOF',
       'BUJAU', 'ALCY', 'BOWNU', 'APGE', 'AIMBU', 'ABLV', 'BOWN', 'BUJA', 'ATPC', 'ARM', 'ANL', 'ABVX', 'ATGL', 'CREV', 'AITRU', 'ANSCU',
       'CRGX', 'ABLLL', 'CGBDL', 'AFJKU', 'AAGR', 'BAYAU', 'AONC', 'CAMP']

nasdaq2_symbols = ['COKE', 'DIOD', 'EVRG', 'EXC', 'CBSH', 'CINF', 'CMCSA', 'CMTL', 'COHU', 'DSGR', 'EML', 'ESCA', 'FARM', 'FELE', 'FITB', 'FLXS',
       'DOMH', 'EDUC', 'FEIM', 'CSX', 'CECO', 'ELSE', 'ERIC', 'FONR', 'CBRL', 'CSPI', 'COO', 'CVBF', 'DXR', 'CTAS', 'DYNT', 'FFBC',
       'EXPD', 'FULT', 'CLDX', 'DLHC', 'DJCO', 'FRPH', 'COST', 'CLFD', 'FCNCA', 'DGICB', 'CCEP', 'DXYN', 'FLIC', 'FBNC', 'DXLG', 'CHCO',
       'XRAY', 'FAST', 'CTBI', 'SSP', 'DAIO', 'BOOM', 'CLRO', 'CRUS', 'FRME', 'CGNX', 'EA', 'DGII', 'CSCO', 'EXPO', 'CATY', 'DORM',
       'CYAN', 'FCFS', 'CRVL', 'EZPW', 'ERNA', 'THFF', 'CACC', 'COLB', 'FCEL', 'CENT', 'FUNC', 'CAKE', 'CPSS', 'FRTX', 'CHDN', 'FOSL',
       'FLL', 'FTEK', 'FFIN', 'CNTY', 'FWRD', 'CMCT', 'DAKT', 'CPRT', 'FLEX', 'CCNE', 'CNOB', 'CPSH', 'CZNC', 'DWSN', 'CIVB', 'FRAF',
       'FCBC', 'EFOI', 'CVLG', 'FORD', 'CIGI', 'ENG', 'CWCO', 'DLTR', 'CLMB', 'DSWL', 'CHNR', 'ERIE', 'FFIC', 'CMCO', 'CSGS', 'CENX',
       'DHIL', 'CHKP', 'ESLT', 'FORR', 'ELTK', 'CERS', 'EMKR', 'EEFT', 'CLWT', 'CRESY', 'ESGR', 'EDAP', 'FARO', 'PLCE', 'CHRW', 'FORTY',
       'CTHR', 'DENN', 'COLM', 'CBAN', 'CRAI', 'DXPE', 'FNWD', 'CLAR', 'CTSH', 'CSGP', 'BUSE', 'ELOX', 'CFBK', 'CHMG', 'CZFS', 'FCAP',
       'FMNB', 'FUSB', 'DCOM', 'FXNC', 'DSGX', 'EWBC', 'CVV', 'CWBC', 'FCCO', 'FMBH', 'EXTR', 'FDBC', 'FFIV', 'FISI', 'ECPG', 'EGBN',
       'FNLC', 'CIZN', 'DMRC', 'DHC', 'EBMT', 'EXEL', 'CYTH', 'ENTG', 'SAVA', 'CRIS', 'CRNT', 'CGEN', 'EQIX', 'DRRX', 'EXAS', 'COFS',
       'CODA', 'CCRN', 'CCOI', 'CEVA', 'CME', 'FBMS', 'DMLP', 'CAAS', 'CHSCP', 'FORM', 'CVCO', 'DGICA', 'IMOS', 'EFSC', 'CBFV', 'CRWS',
       'CNVS', 'DZSI', 'EVO', 'DVAX', 'CYCC', 'CZWI', 'CUTR', 'CORT', 'CYTK', 'ELYS', 'CVGI', 'CHCI', 'EYPT', 'CBAT', 'EBTC', 'RAIL',
       'DXCM', 'JVA', 'CTRN', 'EXPE', 'CNSL', 'CYRX', 'CMPR', 'FBIZ', 'CLRB', 'CYCCP', 'FMAO', 'CROX', 'INBK', 'ESEA', 'APPS', 'CTSO',
       'CVLT', 'ESOA', 'EXLS', 'DLPN', 'CPRX', 'FSLR', 'CREX', 'CELH', 'CSBR', 'CENTA', 'ESSA', 'DGLY', 'CLNE', 'FKWL', 'FFNW', 'FTLF',
       'ENSG', 'EPSN', 'FLNT', 'SATS', 'DYAI', 'CRVO', 'FTFT', 'CDXC', 'ERII', 'COMS', 'FSFG', 'CUEN', 'ADD', 'GSM', 'CPIX', 'CJJD',
       'CULL', 'FTNT', 'CHTR', 'ELVA', 'FIBK', 'FPAY', 'CDXS', 'CRMD', 'CHRD', 'EDSA', 'COSM', 'EVGN', 'FRBA', 'SVVC', 'FDUS', 'CHEF',
       'FBIO', 'COCP', 'DTST', 'ENPH', 'CLIR', 'CLPT', 'FSBW', 'FIVE', 'DMAC', 'FGBI', 'CENN', 'FANG', 'ENTA', 'CMRX', 'ESPR', 'CDW',
       'FOXF', 'CHSCO', 'EVOK', 'FATE', 'COMM', 'CRTO', 'FITBI', 'EKSO', 'EIGR', 'EGRX', 'CHSCN', 'CEAD', 'WATT', 'FGF', 'FIVN', 'DARE',
       'LOCO', 'ENLV', 'CHSCM', 'ELDN', 'CYBR', 'CTXR', 'PLAY', 'DBVT', 'CRBP', 'FFWM', 'CHRS', 'FRPT', 'FGEN', 'FCUV', 'CHSCL', 'FNWB',
       'CHEK', 'XELA', 'EPIX', 'CLLS', 'CDTX', 'ETSY', 'ENVB', 'COLL', 'FTAI', 'FSV', 'CETX', 'CNFR', 'CSWI', 'CTMX', 'PMTS', 'CELZ',
       'EQBK', 'DLTH', 'EDIT', 'DRIO', 'CRVS', 'CLSD', 'FHB', 'FLGT', 'MRAM', 'CRSP', 'CLSK', 'CNDT', 'CKPT', 'EAST', 'CETXP', 'FBRX',
       'DUOT', 'EVTV', 'FRSX', 'ESQ', 'NDRA', 'CODX', 'CBUS', 'GMBL', 'FNGR', 'FRGT', 'CSSE', 'BBCP', 'FENC', 'CELC', 'FAT', 'FNKO',
       'FBIOP', 'DNLI', 'CWBR', 'DOGZ', 'CUE', 'EYEN', 'CLGN', 'FRHC', 'EOLS', 'FAMI', 'CRON', 'DTSS', 'ENSC', 'FGFPP', 'DBX', 'CXDO',
       'COGT', 'CLBK', 'CHX', 'DOCU', 'DCTH', 'ROAD', 'EVLO', 'XCUR', 'CLPS', 'EDRY', 'ESGRP', 'DNTH', 'CSSEP', 'ENTX', 'EVER', 'DOMO',
       'CRNX', 'CCB', 'ESTA', 'MYFW', 'CMLS', 'CHR', 'FTDR', 'EQ', 'CLNN', 'ETON', 'ESGRO', 'SXTC', 'CTRM', 'CMMB', 'FUTU', 'FOXA', 'FOX',
       'CYCN', 'CRWD', 'INBKZ', 'DOYU', 'FSEA', 'FULC', 'CSTL', 'DKNG', 'CELU', 'CFB', 'FITBP', 'FITBO', 'CRNC', 'FTAIP', 'DDOG', 'XGN',
       'DUO', 'CNTG', 'CNSP', 'FTAIO', 'EH', 'CURI', 'DCOMP', 'FRES', 'CCAP', 'FCNCP', 'ELVN', 'CLEU', 'DADA', 'CLOV', 'EBON', 'FATBP',
       'CSSEN', 'FTHM', 'IRON', 'CVAC', 'FLUX', 'FRMEP', 'CCNEP', 'FFIE', 'DYN', 'CMPS', 'EVLV', 'CRSR', 'CCCS', 'ELUT', 'EBC', 'CIFR',
       'FHTX', 'FULTP', 'EOSE', 'CLBT', 'CMPO', 'EOSEW', 'EVGO', 'CNXC', 'DCBO', 'DASH', 'HTOO', 'CERT', 'HTOOW', 'COEP', 'DCGO', 'CLVR',
       'CYTHW', 'EVGOW', 'ENVX', 'CGEM', 'CRKN', 'DGHI', 'DPRO', 'ELBM', 'DRVN', 'EZGO', 'CDRO', 'CXAI', 'AFRI', 'CNEY', 'ELTX', 'EVAX',
       'CGNT', 'FORA', 'CNTB', 'FNCH', 'FTAIN', 'EEIQ', 'CPTN', 'CRCT', 'EWTX', 'DSGN', 'ECX', 'ULCC', 'CMPX', 'COIN', 'FGBIP', 'DAVE',
       'FTCI', 'COCH', 'FSBC', 'FYBR', 'FLGC', 'DBGI', 'EJH', 'FLYW', 'DAWN', 'CNTA', 'DLO', 'DALN', 'FEMY', 'IPSC', 'FA', 'MITAU',
       'CFLT', 'ELEV', 'CVRX', 'EVCM', 'HEPS', 'WAVE', 'ERAS', 'CLOEU', 'BASE', 'CTKB', 'DUOL', 'EWCZ', 'CNOBP', 'DATS', 'DATSW', 'DRMA',
       'MITA', 'DFLI', 'FATBB', 'SWSSU', 'DDI', 'CAUD', 'CLOE', 'ESLA', 'DH', 'EZFL', 'ACT', 'FRSH', 'SWSS', 'CCSI', 'EXAI', 'FWRG',
       'BHACU', 'CGTX', 'CLST', 'CNTX', 'CYN', 'ESACU', 'COMSP', 'FLNC', 'TRDA', 'FRLAU', 'FNVTU', 'DPCSU', 'FOSLL', 'CBRGU', 'EXFY',
       'EFSCP', 'CRGO', 'GMBLP', 'FINW', 'BHAC', 'CING', 'REFI', 'FNVT', 'EUDA', 'CFFSU', 'FIAC', 'FRLA', 'FRLAW', 'DTI', 'DPCS', 'CBRG',
       'CJET', 'FCNCO', 'CFSB', 'CSLMU', 'CISO', 'CEG', 'DUETU', 'FGI', 'LATGU', 'CRDO', 'EVGRU', 'CFFS', 'DRCT', 'CSLM', 'DUET', 'LATG',
       'EMBC', 'XELAP', 'CDT', 'XPON', 'EVGR', 'DECAU', 'ESGL', 'CLRCU', 'EDBL', 'OCTO', 'CMRA', 'CLRC', 'DECA', 'FIP', 'ECBK', 'EMCGU',
       'FRZA', 'EMCG', 'CMND', 'ECDA', 'RAYA', 'COYA', 'ENLT', 'CETY', 'FTAIM', 'FORLU', 'BANL', 'CHSN', 'DIST', 'GDTC', 'FORL', 'FISV',
       'ESHA', 'FTRE', 'CSLR', 'ELWS', 'CTNT', 'FTEL', 'CCG', 'DTCK', 'CCGWW', 'FMST', 'FBYD', 'CPBI', 'ELAB', 'FEBO', 'CLVRW', 'CNFRZ', 'FFBW']

nasdaq3_symbols = ['PEP', 'OTTR', 'PKOH', 'BPOP', 'NTRS', 'NWL', 'PATK', 'PCAR', 'PCH', 'PNRG', 'POWL', 'NDSN', 'NSSC', 'PAYX', 'ONB', 'PEBK',
       'MNST', 'PLXS', 'PDEX', 'PTSI', 'OSUR', 'PLAB', 'PMD', 'NBN', 'PPC', 'ODP', 'NEON', 'NEOG', 'PTC', 'PPIH', 'NRIM', 'MNRO',
       'PRGS', 'FIZZ', 'ODFL', 'QCOM', 'POCI', 'NBTB', 'NTIC', 'OFIX', 'PDCO', 'PESI', 'PEBO', 'NATH', 'ORLY', 'PZZA', 'NSYS', 'PFC',
       'MCRI', 'CASH', 'QCRH', 'NAII', 'PTEN', 'OSBC', 'ZEUS', 'NNBR', 'MPAA', 'PRPH', 'PCYO', 'NKTR', 'PENN', 'PWOD', 'PNBK', 'OVBC',
       'NWBI', 'NVEC', 'PAAS', 'OBLG', 'NHTC', 'MYGN', 'POOL', 'OPK', 'PBHC', 'NTAP', 'NWPX', 'NVAX', 'OTEX', 'NICE', 'OCC', 'NBIX',
       'PROV', 'OCFC', 'PEGA', 'OPCH', 'PPBI', 'PSMT', 'OSIS', 'POWI', 'PRDO', 'CNXN', 'NWFL', 'OSPN', 'NTWK', 'PAA', 'OPOF', 'NVDA',
       'NOVT', 'PETS', 'PGC', 'PLPC', 'ORRF', 'NTCT', 'PFBC', 'OMEX', 'PLUG', 'NXPL', 'NKSH', 'OMQS', 'NVMI', 'ON', 'PXLW', 'NTES',
       'PNFP', 'NEWT', 'MDLZ', 'PSTV', 'PRSO', 'PDFS', 'OMCL', 'ONCY', 'PFG', 'PRTG', 'NFLX', 'PFIS', 'NDAQ', 'PRAA', 'PLBC', 'OPHC',
       'PKBK', 'PLUR', 'NTGR', 'MODV', 'OBT', 'OVLY', 'OXSQ', 'NXST', 'OTRK', 'ONCT', 'NEO', 'SEED', 'NURO', 'NYMT', 'PSEC', 'NEPH',
       'MPWR', 'MTEM', 'MORN', 'OFLX', 'OPBK', 'PARA', 'PERI', 'NCPL', 'NECB', 'FRST', 'PALT', 'PTMN', 'PMN', 'QQQX', 'NCMI', 'PALI',
       'ORMP', 'PAYS', 'NFBK', 'OPRX', 'OESX', 'NWE', 'OCSL', 'POET', 'PRIM', 'MYRG', 'MULN', 'BPOPM', 'OPI', 'NATR', 'OMER', 'PFIE',
       'NEGG', 'OPXS', 'POAI', 'NXPI', 'PACB', 'PSHG', 'OFED', 'PFX', 'OXLC', 'PCRX', 'NMFC', 'NVFY', 'ONVO', 'NUWE', 'ORGS', 'COOP',
       'PBYI', 'PHIO', 'PANW', 'MVBF', 'PFMT', 'OLB', 'MRCC', 'OFS', 'PRTA', 'PMCB', 'IPDN', 'PPSI', 'QIWI', 'NRC', 'NWS', 'NWSA',
       'PTCT', 'NSTG', 'NDLS', 'PGEN', 'PINC', 'NVEE', 'PBPB', 'PAGP', 'NMIH', 'PANL', 'NGNE', 'PCSA', 'PCTY', 'PULM', 'OXBR', 'PAHC',
       'NUZE', 'NAVI', 'STKS', 'OCUL', 'PETV', 'PRQR', 'TARA', 'OCGN', 'NMRD', 'PIRS', 'QRVO', 'OPGN', 'NAOV', 'NEXT', 'NTRA', 'PYPL',
       'OLLI', 'PVBC', 'PDSB', 'NVCR', 'PRPL', 'PXS', 'PLYA', 'PPBT', 'OCX', 'NNDM', 'PLSE', 'MBRX', 'OTLK', 'PAVM', 'NRBO', 'MYSZ',
       'PTGX', 'NTNX', 'PHUN', 'PRTH', 'POLA', 'NISN', 'PBLA', 'ORGO', 'NODK', 'OKTA', 'NCSM', 'OVID', 'MOGO', 'BPRN', 'PRPO', 'MBIO',
       'NCNA', 'PDLB', 'KIDS', 'OPTN', 'MDB', 'NAAS', 'EYE', 'NYMTN', 'OSW', 'NRXP', 'NMRK', 'PLL', 'OSS', 'MOTS', 'NMTC', 'LPRO',
       'NKLA', 'STIM', 'PDD', 'OPRA', 'PCB', 'OCCI', 'NIU', 'PT', 'MRNA', 'QFIN', 'NFE', 'DTIL', 'OXSQZ', 'PLMR', 'NXTC', 'OGI', 'PSNL',
       'PBFS', 'OPRT', 'PTON', 'PNTG', 'NYMTM', 'PAVS', 'PGNY', 'PHAT', 'PROF', 'NTRSO', 'PARAA', 'PROC', 'MNPR', 'MNTS', 'PRCH', 'OXLCP',
       'ONEW', 'PASG', 'NWTN', 'ORIC', 'NVVE', 'OCFCP', 'PCTTU', 'ONBPP', 'NEOV', 'PNFPP', 'PLRX', 'TOI', 'OPEN', 'ONBPO', 'OPINL', 'PYPD',
       'NKTX', 'PSTX', 'PCT', 'NUKK', 'NRIX', 'OBIO', 'NAUT', 'NNOX', 'OTRKP', 'PLBY', 'PRFX', 'ORGN', 'OM', 'PTVE', 'PMVP', 'PRLD',
       'LUNG', 'SQFT', 'OPT', 'PAYO', 'PRAX', 'MLTX', 'NVEI', 'NN', 'PRTC', 'OLMA', 'PWP', 'PTPI', 'ONDS', 'MNY', 'MNYWW', 'PUBM',
       'NBTX', 'OCG', 'MYPSW', 'MYPS', 'PHAR', 'NCRA', 'MSGM', 'WOOF', 'OCAXU', 'PLTK', 'MNTK', 'PAX', 'NEWTZ', 'NLSP', 'NLSPW', 'PHVS',
       'PRST', 'NAMS', 'NAMSW', 'NEXI', 'PPTA', 'NVOS', 'PECO', 'MLEC', 'OCAX', 'MOVE', 'NBSTU', 'MOND', 'PIII', 'PGY', 'NPCE', 'OCCIO',
       'PTIX', 'NYXH', 'PRVA', 'NBST', 'OCS', 'PSNY', 'OTLY', 'OPAL', 'OXSQG', 'MMV', 'SQFTP', 'MOLN', 'GLUE', 'ONMD', 'CPOP', 'NYMTL',
       'PROK', 'NXTP', 'PBBK', 'PRE', 'PFTAU', 'PYCR', 'OB', 'NUVL', 'OMGA', 'KITT', 'NOVVU', 'OXLCO', 'KTTA', 'PRCT', 'PFTA', 'OABI',
       'OLPX', 'NOVV', 'NTRB', 'NTRBW', 'PYXS', 'NVTS', 'PTLO', 'OFSSH', 'PEGRU', 'NRDS', 'MCAAU', 'NPABU', 'OCEA', 'MYNA', 'PFXNZ',
       'NYMTZ', 'MCAGU', 'OP', 'MCAG', 'OCCIN', 'NRSN', 'ONYX', 'PRLHU', 'NXGL', 'MCAA', 'NVNI', 'NPAB', 'OXLCZ', 'PPYAU', 'NSTS', 'NVAC',
       'NVX', 'NVCT', 'MODD', 'PRLH', 'ONCO', 'PWUPU', 'PPYA', 'PLAOU', 'PEGY', 'NUTX', 'PWUP', 'OST', 'PLAO', 'PEPG', 'ACDC', 'OKYO',
       'LIFW', 'PEV', 'OXLCN', 'PSNYW', 'PGYWW', 'ONFO', 'PXMD', 'NXL', 'LIFWW', 'NYAX', 'NXU', 'QOMOU', 'PRME', 'QOMO', 'OSA', 'NXT',
       'PTHRU', 'MVLA', 'NB', 'OMH', 'OAKUU', 'MGRM', 'OAKU', 'OAKUR', 'PWM', 'NETDU', 'ODD', 'PRZO', 'PXDT', 'NEWTI', 'NETD', 'PODC',
       'NWGL', 'NMRA', 'NKGN', 'PMEC', 'EGOX', 'MURA', 'NMFCZ', 'NUKKW', 'NESR']

nasdaq4_symbols = ['TXN', 'SGC', 'TER', 'TRNS', 'RAND', 'SENEB', 'SIGI', 'SMTC', 'TRMK', 'TWIN', 'UG', 'UMBF', 'USAU', 'USEG', 'USLM', 'SIEB',
       'UFCS', 'TAYD', 'SEIC', 'RGLD', 'VXRT', 'TRST', 'VALU', 'RCMT', 'SLM', 'RELL', 'RDI', 'SBCF', 'SHYF', 'SWKS', 'SFNC', 'GROW',
       'ROST', 'STKL', 'RMCF', 'TROW', 'RGEN', 'SKYW', 'REFR', 'UNAM', 'TATT', 'UBSI', 'THMO', 'SNFCA', 'FUND', 'VLY', 'TRMB', 'QDEL',
       'REGN', 'STRL', 'TTEK', 'ROP', 'STAA', 'SCHL', 'SNPS', 'STBA', 'RNST', 'SBUX', 'STRS', 'TRIB', 'ULBI', 'RCKY', 'UEIC', 'SGA',
       'UBCP', 'SCVL', 'SNT', 'SYBT', 'SANM', 'TCBK', 'RAVE', 'TLF', 'RVSB', 'REG', 'URBN', 'UFPI', 'RDUS', 'SHOO', 'UFPT', 'STCN',
       'RGCO', 'SGMA', 'TSCO', 'SILC', 'SCSC', 'SNGX', 'TENX', 'WULF', 'RFIL', 'SASR', 'SMTI', 'SMBC', 'BSRR', 'SYPR', 'SIRI', 'SSYS',
       'TSEM', 'SEEL', 'VECO', 'USAP', 'UPBD', 'STRT', 'SNEX', 'STGW', 'TAIT', 'SBGI', 'SVC', 'SMSI', 'RICK', 'SMID', 'TTNP', 'SGRP',
       'OLED', 'STRM', 'TCX', 'RUSHB', 'STRA', 'SSRM', 'TTEC', 'TACT', 'SRCL', 'SEAC', 'VEON', 'STLD', 'RDNT', 'UNTY', 'SSB', 'VCEL',
       'TTWO', 'RMBS', 'SBET', 'RYAAY', 'SRPT', 'SLP', 'SIGA', 'RDCM', 'TSBK', 'RMTI', 'VRSN', 'SRDX', 'SPNS', 'UVSP', 'SOFO', 'SBSI',
       'SENEA', 'RBCAA', 'SNBR', 'SBFG', 'USIO', 'UBFO', 'UTMD', 'SCKT', 'SHEN', 'SOTK', 'TOWN', 'UONE', 'SLNH', 'SBAC', 'UTHR', 'SALM',
       'MDRX', 'QMCO', 'UNB', 'SWBI', 'SRNE', 'SWKH', 'RDWR', 'QUIK', 'SIFY', 'SFST', 'RDIB', 'UTSI', 'SLAB', 'SGMO', 'RBBN', 'UONEK',
       'SOHU', 'SPTN', 'TTMI', 'RIGL', 'VRME', 'RGP', 'SHBI', 'RIBT', 'RCAT', 'SYNA', 'SBRA', 'VRNT', 'SNY', 'RRGB', 'TZOO', 'SAIA',
       'SAFT', 'STX', 'MARK', 'TCBI', 'SVA', 'RUSHA', 'SMBK', 'TCOM', 'UCTT', 'STRR', 'TIO', 'TOPS', 'TXRH', 'SPOK', 'NCTY', 'SOHO',
       'CREG', 'ULH', 'SPCB', 'SIMO', 'SLMBP', 'TSAT', 'GASS', 'SSKN', 'BCAL', 'UAL', 'VNDA', 'QRTEA', 'QRTEB', 'SEVN', 'SNCR', 'SSBI',
       'TAOP', 'SONN', 'SNOA', 'QUBT', 'SMCI', 'TMUS', 'TFSL', 'REED', 'TXMD', 'SLNG', 'TTGT', 'TRS', 'ULTA', 'SBLK', 'TITN', 'TPCS',
       'SFBC', 'SHIP', 'SLS', 'TROO', 'SGLY', 'TOMZ', 'THTX', 'SOBR', 'TBNK', 'RCON', 'VRSK', 'ROIC', 'QRHC', 'SLRC', 'QNST', 'SANG',
       'SSNC', 'RVYL', 'SPSC', 'TGTX', 'RCM', 'SANW', 'TSLA', 'QIPT', 'TIPT', 'VRA', 'HEAR', 'RSSS', 'LEDS', 'LAB', 'SSSS', 'TRIP',
       'VSTM', 'SUPN', 'TNXP', 'TTSH', 'QLYS', 'RGLS', 'TVTX', 'TPST', 'SRAX', 'RDHL', 'RZLT', 'STAF', 'SAMG', 'SFM', 'ANY', 'VCYT',
       'TNDM', 'RARE', 'TRVN', 'RVNC', 'SINT', 'SMLR', 'VRNS', 'SABR', 'SPWH', 'SCYX', 'TOUR', 'TBPH', 'TRUE', 'RLMD', 'SAGE', 'TRUP',
       'TTOO', 'VBTX', 'UPLD', 'TFIN', 'SLNO', 'VERB', 'SLRX', 'TCON', 'RCKT', 'SMMT', 'TANH', 'SEDG', 'UNIT', 'SCNI', 'QLGN', 'MCRB',
       'RPD', 'RUN', 'RMNI', 'RGNX', 'SGRY', 'SYBX', 'RMR', 'SPI', 'SNDX', 'RIOT', 'SYRE', 'SCWX', 'RRR', 'SYRS', 'TPIC', 'SRTS', 'TCMD',
       'QNRX', 'SOHOB', 'TTD', 'SISI', 'RSLS', 'WORX', 'SND', 'SNES', 'VREX', 'RMBL', 'METC', 'SVRA', 'URGN', 'VERI', 'SSTI', 'SGBX',
       'PIXY', 'SMPL', 'RBB', 'RDFN', 'REKR', 'PETZ', 'SECO', 'ROKU', 'RYTM', 'SOHOO', 'VERO', 'SPRO', 'STEL', 'SBT', 'SFIX', 'RETO',
       'QTRX', 'SURG', 'SLDB', 'SLGL', 'RENB', 'TRMD', 'TH', 'AIHS', 'RDVT', 'THRY', 'UBX', 'SRRK', 'UXIN', 'SGML', 'RPAY', 'TLRY',
       'REPL', 'TENB', 'SONO', 'VCNX', 'STRO', 'UPWK', 'VLYPO', 'VLYPP', 'SIBN', 'RVPH', 'STNE', 'TWST', 'TC', 'TLSA', 'TBLT', 'RBKB',
       'SLE', 'SNAX', 'SJ', 'TIGR', 'TW', 'SOHON', 'SY', 'TMDX', 'RRBI', 'TRVI', 'QNCX', 'SPFI', 'SONM', 'TECTP', 'STOK', 'REAL', 'RMBI',
       'SNDL', 'STRRP', 'SWTX', 'TFFP', 'RAPT', 'UK', 'TELA', 'UGRO', 'SITM', 'SPT', 'REYN', 'SDGR', 'RVMD', 'SDOT', 'PCVX', 'RPRX',
       'TFINP', 'RPTX', 'QH', 'RLAY', 'EDTK', 'TALK', 'VSTA', 'RXT', 'QRTEP', 'TNGX', 'SLN', 'STEP', 'TSHA', 'SYTA', 'SPRB', 'STTK',
       'TARS', 'ROOT', 'SHOT', 'QSI', 'REVB', 'TLS', 'SHC', 'RKLB', 'SIGIP', 'SEER', 'ROIV', 'SNPX', 'UPST', 'SOFI', 'RSVR', 'REAX',
       'SILO', 'SRZN', 'REE', 'RSVRW', 'SHLS', 'TIRX', 'TRIN', 'RNW', 'RNWWW', 'SANA', 'SNSE', 'TERN', 'TLSI', 'EPOW', 'RELI', 'SABS',
       'TLSIW', 'TLIS', 'IDAI', 'TWLVU', 'SCLX', 'SYM', 'THCH', 'STKH', 'SOND', 'SWVL', 'SNCY', 'ICU', 'UPC', 'SATL', 'TCBIO', 'TDUP',
       'UHG', 'EM', 'MDAI', 'SBIG', 'WTO', 'VCSA', 'RUM', 'RXRX', 'SDA', 'SKYT', 'RGTI', 'TMCI', 'UROY', 'RMCO', 'VALN', 'TRML', 'VERA',
       'SLDP', 'SNTI', 'OMIC', 'TASK', 'TBIO', 'UPXI', 'TBLA', 'THCPU', 'SNCRL', 'RNAZ', 'SNTG', 'UNCY', 'METCL', 'RPID', 'SERA', 'SGHT',
       'RGC', 'TCBS', 'TCRX', 'VEEE', 'SOPH', 'USCB', 'TBLD', 'HOOD', 'RLYB', 'RANI', 'RXST', 'TNYA', 'SSBK', 'SHFS', 'SLNHP', 'RNXT',
       'SPRC', 'TYGO', 'THCP', 'TMC', 'SRAD', 'TMCWW', 'TWKS', 'TYRA', 'RELY', 'STER', 'SHPW', 'VGAS', 'SDIG', 'RWAY', 'VTYX', 'RENT',
       'USCTU', 'UDMY', 'RGF', 'SOPA', 'SWAG', 'TCBX', 'RIVN', 'TIVC', 'VAXX', 'SEV', 'LITM', 'ROCLU', 'TLGYU', 'SMX', 'TGAAU', 'SIDU',
       'IVCPU', 'RCACU', 'SSSSL', 'SLND', 'SPEC', 'USCT', 'ROCL', 'VSTE', 'THAR', 'RDZN', 'TPG', 'DCFC', 'TETEU', 'TLGY', 'OPTX', 'TGAA',
       'SKYX', 'TCBP', 'SBFM', 'SMFL', 'IVCP', 'VMCAU', 'TETE', 'RFACU', 'RVSN', 'STSS', 'RFAC', 'VMCA', 'TNON', 'SOUN', 'TOP', 'SVRE',
       'SKGRU', 'USEA', 'TRINL', 'RWAYL', 'TGL', 'REBN', 'SKGRW', 'SKGR', 'STBX', 'SHPH', 'THRD', 'SVMH', 'SVIIU', 'SVII', 'SNAL', 'RWAYZ',
       'SKWD', 'QSG', 'GPCR', 'TORO', 'STHO', 'TMTCU', 'TBMCR', 'SFWL', 'SYT', 'SHLT', 'VCIG', 'UCAR', 'USGO', 'TMTC', 'TBMC', 'LAES',
       'METCB', 'SGMT', 'TSBX', 'SPGC', 'SRM', 'SWIN', 'REGCO', 'REGCP', 'SEZL', 'SPPL', 'SGD', 'SRBK', 'TURB', 'SYRA', 'SWKHL', 'QETAU',
       'SPKLU', 'ULY', 'SHIM', 'RR', 'SPKL', 'QETA', 'GSIB', 'SBNY', 'TCBC', 'SMAP', 'TGVCW']

nasdaq5_symbols = ['XRX', 'VLGEA', 'XEL', 'WDFC', 'WDC', 'VTRS', 'WABC', 'WBA', 'WEYS', 'ZION', 'VIRC', 'WEN', 'VSEC', 'WAFD', 'TURN', 'SRCE',
       'XOMA', 'WERN', 'WSFS', 'WSBC', 'WASH', 'VOD', 'VICR', 'VRTX', 'ZBRA', 'WRLD', 'VOXX', 'WINA', 'VIAV', 'WWD', 'WVVI', 'WINT',
       'VBFC', 'SCWO', 'WHLM', 'WLFC', 'VSAT', 'EGHT', 'WTFC', 'VERU', 'WTBA', 'YORW', 'VABK', 'ZD', 'FLWS', 'WTW', 'WKSP', 'WW', 'WNEB',
       'WYNN', 'YHGJ', 'ZIVO', 'ZYXI', 'ZUMZ', 'WBD', 'XTLB', 'VIRX', 'WSBF', 'YTEN', 'WFCF', 'WLDN', 'ZIONP', 'WMPN', 'WPRT', 'VRTS',
       'CNET', 'VIVK', 'VUZI', 'WKHS', 'XWEL', 'VC', 'XXII', 'VNET', 'VTGN', 'ZG', 'ZTEK', 'VISL', 'VS', 'VTSI', 'XELB', 'WDAY', 'WHLR',
       'WHF', 'ZIONO', 'ZIONL', 'WIX', 'XNCR', 'WB', 'VNOM', 'VRDN', 'XNET', 'XENE', 'VANI', 'WHLRP', 'XBIT', 'VIRT', 'ZVRA', 'VKTX',
       'VVPR', 'WING', 'WTFCM', 'Z', 'WSC', 'VYGR', 'WVE', 'VEV', 'XBIO', 'WVVIP', 'YTRA', 'VIASP', 'VRRM', 'VRNA', 'ZYME', 'ATNF', 'WHLRD',
       'ZKIN', 'ZLAB', 'XFOR', 'VYNE', 'VCTR', 'ZS', 'BBIG', 'WRAP', 'VRCA', 'XERS', 'WISA', 'YI', 'YMAB', 'VIOT', 'BCOW', 'WKEY',
       'VFF', 'ZM', 'WAFU', 'YJ', 'XPEL', 'VMD', 'JFU', 'TXG', 'MAPS', 'VIR', 'KRKR', 'ETNB', 'XP', 'ZCMD', 'WIMI', 'ZNTL', 'WTFCP',
       'VINC', 'WMG', 'ZI', 'VRM', 'VERX', 'VITL', 'VOXR', 'WSBCP', 'ME', 'VMAR', 'YQ', 'XOS', 'FDMT', 'VVOS', 'XOMAP', 'MASS', 'SEATW',
       'WFRD', 'VSSYW', 'VINP', 'WAFDP', 'VOR', 'DSP', 'VRPX', 'VIEW', 'XOMAO', 'HOWL', 'XBP', 'WALD', 'WALDW', 'VMEO', 'DIBS', 'VERV',
       'XMTR', 'ZENV', 'VBNK', 'WHLRL', 'WINVU', 'XRTX', 'PET', 'WINV', 'VLCN', 'SEAT', 'WEST', 'COCO', 'XLO', 'TSVT', 'ZAPP', 'WTMAU',
       'VIGL', 'WAVSU', 'TKLF', 'WTMA', 'ZVSA', 'ZIMV', 'FEAM', 'WAVS', 'YOTAU', 'GV', 'YOTA', 'VRAX', 'YOSH', 'WLDS', 'AIXI', 'ZURA',
       'WLGS', 'SXTP', 'VFS', 'VFSWW', 'WHFCL', 'VSME', 'WBUY', 'XBIOW']


